Add more logging for failed builds

diff --git a/build b/build
--- a/build
+++ b/build
@@ -5,6 +5,15 @@ do_clean=false
 log() {
 	echo "[$0] $@"
 }
+handle_fail() {
+	local status=$?
+	if [[ $status -ne 0 ]]; then
+		log "Something failed (status=$status)."
+		exit $status
+	fi
+}
+trap handle_fail EXIT
+
 compile() {
 	local name="$1"
 	log "Compiling $name..."
